while true do
	script.Parent.union1.BrickColor = BrickColor.Blue()
	script.Parent.union2.BrickColor = BrickColor.Blue()
	script.Parent.union3.BrickColor = BrickColor.Blue()
	script.Parent.union4.BrickColor = BrickColor.Blue()
	script.Parent.union5.BrickColor = BrickColor.Blue()
	script.Parent.union6.BrickColor = BrickColor.Blue()
	script.Parent.union7.BrickColor = BrickColor.Blue()
	script.Parent.union8.BrickColor = BrickColor.Blue()
	script.Parent.union9.BrickColor = BrickColor.Blue()
	script.Parent.union10.BrickColor = BrickColor.Blue()
	script.Parent.union11.BrickColor = BrickColor.Blue()
	script.Parent.union12.BrickColor = BrickColor.Blue()
	wait(3)
	script.Parent.union1.BrickColor = BrickColor.Red()
	script.Parent.union2.BrickColor = BrickColor.Red()
	script.Parent.union3.BrickColor = BrickColor.Red()
	script.Parent.union4.BrickColor = BrickColor.Red()
	script.Parent.union5.BrickColor = BrickColor.Red()
	script.Parent.union6.BrickColor = BrickColor.Red()
	script.Parent.union7.BrickColor = BrickColor.Red()
	script.Parent.union8.BrickColor = BrickColor.Red()
	script.Parent.union9.BrickColor = BrickColor.Red()
	script.Parent.union10.BrickColor = BrickColor.Red()
	script.Parent.union11.BrickColor = BrickColor.Red()
	script.Parent.union12.BrickColor = BrickColor.Red()
	wait(3)
	script.Parent.union1.BrickColor = BrickColor.Green()
	script.Parent.union2.BrickColor = BrickColor.Green()
	script.Parent.union3.BrickColor = BrickColor.Green()
	script.Parent.union4.BrickColor = BrickColor.Green()
	script.Parent.union5.BrickColor = BrickColor.Green()
	script.Parent.union6.BrickColor = BrickColor.Green()
	script.Parent.union7.BrickColor = BrickColor.Green()
	script.Parent.union8.BrickColor = BrickColor.Green()
	script.Parent.union9.BrickColor = BrickColor.Green()
	script.Parent.union10.BrickColor = BrickColor.Green()
	script.Parent.union11.BrickColor = BrickColor.Green()
	script.Parent.union12.BrickColor = BrickColor.Green()
	wait(3)
	script.Parent.union1.BrickColor = BrickColor.Yellow()
	script.Parent.union2.BrickColor = BrickColor.Yellow()
	script.Parent.union3.BrickColor = BrickColor.Yellow()
	script.Parent.union4.BrickColor = BrickColor.Yellow()
	script.Parent.union5.BrickColor = BrickColor.Yellow()
	script.Parent.union6.BrickColor = BrickColor.Yellow()
	script.Parent.union7.BrickColor = BrickColor.Yellow()
	script.Parent.union8.BrickColor = BrickColor.Yellow()
	script.Parent.union9.BrickColor = BrickColor.Yellow()
	script.Parent.union10.BrickColor = BrickColor.Yellow()
	script.Parent.union11.BrickColor = BrickColor.Yellow()
	script.Parent.union12.BrickColor = BrickColor.Yellow()
	wait(3)
end
